name = "createleme"
author = "apk modificado"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f297ec4b6599922c75722add506e2ce26e740417e5f5a72a805704e9f1fe5525"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
