name = "createleme"
author = "apk modificado"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c87341cc64e121fc46a4eae88317202f64fd95de24dd7c0e1603758b733e439c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"

[options]
acceptable-game-versions = []
