name = "createleme"
author = "apk modificado"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb8cac68a987f7fe78b323124dca97d6fd0a5068b023711664d12c7834e39242"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
